name: Continuous Integration and Delivery

on: [push]

env:
  IMAGE: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/summarizer

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./project/Dockerfile.prod \
            "./project"
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:latest

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: main
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./project/Dockerfile.prod \
            "./project"
      - name: Run container
        run: |
          docker run \
            -d \
            --name box-metadata \
            -e PORT=8765 \
            -e ENVIRONMENT=dev \
            -e TESTING=1 \
            -p 5003:8765 \
            ${{ env.IMAGE }}:latest
      - name: Debug
        run:  |
          docker exec box-metadata pwd
          docker exec box-metadata ls -laF
          docker exec box-metadata whoami
          docker exec box-metadata ls -laF app
          docker exec box-metadata echo "${{ secrets.CONFIG_JSON }}"
      - name: Create .jwt.config.json
        run: docker exec box-metadata echo "${{ secrets.CONFIG_JSON }}" | base64 -d > app/.jwt.config.json
      - name: Create .env
        run: docker exec box-metadata echo "${{ secrets.ENV }}" | base64 -d > app/.env
      - name: Pytest
        run: docker exec box-metadata python -m pytest .
      - name: Flake8
        run: docker exec box-metadata python -m flake8 .
      - name: Black
        run: docker exec box-metadata python -m black . --check
      - name: isort
        run: docker exec box-metadata python -m isort . --check-only